
import EnumValue = require('dw/value/EnumValue')
import MarkupText = require('dw/content/MarkupText');
import MediaFile = require('dw/content/MediaFile');

// autogeneratedfile - 'c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml'
declare global {
    module ICustomAttributes {

		interface Product {
			/**
			* Labor
			* @group extendMfrWarranty - Extend Manufacturer Warranty
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#5) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#34)
			*/
			mfrWarrantyLabor: string | null;

			/**
			* Parts
			* @group extendMfrWarranty - Extend Manufacturer Warranty
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#17) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#33)
			*/
			mfrWarrantyParts: string | null;

		}
		interface ProductLineItem {
			/**
			* Extend Parent LineItem UUID
			* 
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#40) 
			*/
			parentLineItemUUID: string | null;

			/**
			* Persistent UUID
			* 
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#47) 
			*/
			persistentUUID: string | null;

			/**
			* Extend Contract ID
			* @group Extend - Extend
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#54) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#65)
			*/
			extendContractId: ReadonlyArray<string> 

		}
		interface SitePreferences {
			/**
			* Access Token

				Extend Access Token
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#71) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#143)
			*/
			extendAccessToken: string | null;

			/**
			* Enable Up-sell in Cart
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#79) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#150)
			*/
			extendCartUpsellSwitch: boolean | null;

			/**
			* Enable Extend
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#86) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#147)
			*/
			extendGlobalSwitch: boolean | null;

			/**
			* Image View Type
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#93) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#145)
			*/
			extendImageViewType: string | null;

			/**
			* Enable in PDP
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#101) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#148)
			*/
			extendPDPSwitch: boolean | null;

			/**
			* Enable Up-sell in PDP
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#108) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#149)
			*/
			extendPDPUpsellSwitch: boolean | null;

			/**
			* Extend SDK

				URL for the Javascript Extend SDK
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#115) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#146)
			*/
			extendSDK: string | null;

			/**
			* Store ID

				Extend Store ID
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#124) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#144)
			*/
			extendStoreID: string | null;

			/**
			* Use Extend In Production Mode
			* @group Extend - Extend Configurations
			* @source [attribute](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#132) | [group](file:c:\Projects\helloextend\metadata\meta\system-objecttype-extensions.xml#151)
			*/
			isExtendProductionMode: boolean | null;

		}
	}
}
